import Head from 'next/head'
import { HeroComponent, SectionFeature, SectionAboutProduct } from '../components'


export default function Home() {
  return (
    <>
      <Head>
        <title>Drone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroComponent />
      <SectionFeature />
      <SectionAboutProduct />
    </>
  )
}
